version: '3.4'

services:
  docker.worker:
    image: ${DOCKER_REGISTRY-}dockerworker
    build:
      context: .
      dockerfile: src/Docker.Worker/Dockerfile
    container_name: Docker.Worker
    depends_on:
      - docker.mssql
      - docker.rabbitmq

  docker.web:
    image: ${DOCKER_REGISTRY-}dockerweb
    build:
      context: .
      dockerfile: src/Docker.Web/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    container_name: Docker.Web
    depends_on:
      - docker.mssql
      - docker.rabbitmq
  
  docker.mssql:
    image: "mcr.microsoft.com/mssql/server"
    ports: 
      - "11433:1433"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    container_name: Docker.Mssql

  docker.rabbitmq:
    image: "masstransit/rabbitmq"
    ports: 
      - "15672:15672"
      - "5672:5672"
    container_name: Docker.RabbitMq