apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: docker-poc
  name: docker-poc-web
  labels:
    app: docker-poc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-poc-web
  strategy: {}
  template:
    metadata:
      labels:
        app: docker-poc-web
    spec:
      containers:
      - name: docker-poc-web
        image: christiaanderidder/docker-poc-web
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}