apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker\docker-compose.yml -o .\k8s
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: docker-poc-web
  name: docker-poc-web
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  - name: "8443"
    port: 8443
    targetPort: 443
  selector:
    io.kompose.service: docker-poc-web
  type: LoadBalancer
status:
  loadBalancer: {}
