apiVersion: v1
kind: Service
metadata:
  namespace: docker-poc
  name: docker-poc-mssql
  labels:
    app: docker-poc-mssql
spec:
  ports:
  - name: "mssql"
    port: 1433
    targetPort: 1433
  selector:
    app: docker-poc-mssql
