apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: docker-poc-ingress
spec:
  tls:
  - hosts:
    - www.docker-poc.local
    - rabbitmq.docker-poc.local
    secretName: docker-poc-tls
  rules:
  - host: www.docker-poc.local
    http:
      paths:
      - backend:
          serviceName: docker-poc-web
          servicePort: 80
  - host: rabbitmq.docker-poc.local
    http:
      paths:
      - backend:
          serviceName: docker-poc-rabbitmq
          servicePort: 80