version: '3.4'

services:
  docker-poc-worker:
    image: christiaanderidder/docker-poc-worker
    build:
      context: ../
      dockerfile: src/Docker.Worker/Dockerfile
    networks:
      - internal
    depends_on:
      - docker-poc-mssql
      - docker-poc-rabbitmq

  docker-poc-web:
    image: christiaanderidder/docker-poc-web
    build:
      context: ../
      dockerfile: src/Docker.Web/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - internal
    depends_on:
      - docker-poc-mssql
      - docker-poc-rabbitmq
  
  docker-poc-mssql:
    image: "mcr.microsoft.com/mssql/server"
    ports: 
      - "11433:1433"
    networks:
      - internal
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"

  docker-poc-rabbitmq:
    image: "masstransit/rabbitmq"
    ports: 
      - "15672:15672"
      - "5672:5672"
    networks:
      - internal
networks: 
  internal: