apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: docker-poc
build:
  artifacts:
    - image: docker-poc-web
      context: ../
      docker: 
        dockerfile: src/Docker.Web/Dockerfile
    - image: docker-poc-worker
      context: ../
      docker: 
        dockerfile: src/Docker.Worker/Dockerfile
deploy:
  kubectl:
    manifests:
    - ..\k8s\*.yaml
